{
 "title": "API Server",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Total QPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(apiserver_request_count[3m]))",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(increase(apiserver_request_latencies_sum[3m]) / apiserver_request_latencies_count)",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "QPS by Response Code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(apiserver_request_count{code!=\"0\"}[3m])) by (code) > 0",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "QPS by Server",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(apiserver_request_count{code!=\"0\"}[3m])) by (instance) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Latencies by Verb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(increase(apiserver_request_latencies_sum[3m])) by (verb) / sum(apiserver_request_latencies_count) by (verb)",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Response Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(apiserver_response_sizes_sum[3m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Latencies by Resource",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(increase(apiserver_request_latencies_sum[3m])) by (resource) / sum(apiserver_request_latencies_count) by (resource))",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Longrunning Gagues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_longrunning_gauge) by (verb)",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Audit Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(apiserver_audit_event_total{job=\"apiserver\"}[3m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}