{
 "title": "Kubernetes Nodes Overview",
 "description": "Critical metrics of k8s host servers",
 "tags": [
  "kubernetes",
  "metrics"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(node_boot_time_seconds)" }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(machine_cpu_cores)" }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - sum(node_memory_MemFree_bytes) / sum(node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{device!~\"rootfs|tmpfs\",mountpoint!~\"/|/boot|/home|/tmp|/usr|/var|.*pv[0-9]*\"})"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - sum(node_filesystem_avail_bytes{device!~\"rootfs|tmpfs\",mountpoint!~\"/|/boot|/home|/tmp|/usr|/var|.*pv[0-9]*\"}) / sum(sum(node_filesystem_size_bytes{device!~\"rootfs|tmpfs\",mountpoint!~\"/|/boot|/home|/tmp|/usr|/var|.*pv[0-9]*\"}))"
    }
   ]
  },
  {
   "title": "Network RX",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"cali.*|docker.*\"}[3m]))"
    }
   ]
  },
  {
   "title": "Network TX",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!~\"cali.*|docker.*\"}[3m]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode!=\"idle\"}[3m])) by (instance) / count(node_cpu_frequency_hertz) by (instance) or sum(increase(node_cpu_seconds_total{mode!=\"idle\"}[3m])) by (instance) / sum(increase(node_cpu_seconds_total[3m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Storage Usage (excl. /)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{device!~\"rootfs|tmpfs\",mountpoint!~\"/|/boot|/home|/tmp|/usr|/var|.*pv[0-9]*\"}) by (instance) - sum(node_filesystem_free_bytes{device!~\"rootfs|tmpfs\",mountpoint!~\"/|/boot|/home|/tmp|/usr|/var|.*pv[0-9]*\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load5",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "node_load5", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Storage Usage (/)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{device!~\"rootfs|tmpfs\",mountpoint=\"/\"}) by (instance) - sum(node_filesystem_free_bytes{device!~\"rootfs|tmpfs\",mountpoint=\"/\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk I/O Rates (NVMe Drives)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{device=~\"nvme.*\"}[3m])) by (instance) + sum(rate(node_disk_written_bytes_total{device=~\"nvme.*\"}[3m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk I/O Rates (SAS/SSD Drives)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{device=~\"sd.*\"}[3m])) by (instance) + sum(rate(node_disk_written_bytes_total{device=~\"sd.*\"}[3m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Traffic (Receive)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device!~\"cali.*|docker.*\"}[3m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Traffic (Transmit)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{device!~\"cali.*|docker.*\"}[3m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}