{
 "title": "Tidb-Cluster-Node_exporter",
 "description": "Prometheus for system metrics. \r\nLoad, CPU, RAM, network, process ... ",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(node_boot_time_seconds,instance)"
   },
   {
    "name": "buddyinfozone",
    "query": "label_values(node_buddyinfo_blocks,zone)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virtual CPUs",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(node_cpu_seconds_total{instance=\"$host\", mode=\"user\"})"
      }
     ]
    },
    {
     "title": "Total RAM",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$host\"}"
      }
     ]
    },
    {
     "title": "Total Swap",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "node_memory_SwapTotal_bytes{instance=\"$host\"}"
      }
     ]
    },
    {
     "title": "System Uptime",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 2 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "node_time_seconds{instance=\"$host\"} - node_boot_time_seconds{instance=\"$host\"}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_time%7Binstance%3D%5C%22%24host%5C%22%7D%20-%20node_boot_time%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A25%22%2C%22step_input%22%3A%22%22%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "Node_exporter version",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "expr": "node_exporter_build_info" }
     ]
    },
    {
     "title": "CPU Used",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "1 - (sum(rate(node_cpu_seconds_total{instance=\"$host\", mode=\"idle\"}[$interval])) / count(node_cpu_seconds_total{instance=\"$host\", mode=\"idle\"}) or sum(irate(node_cpu_seconds_total{instance=\"$host\", mode=\"idle\"}[30s])) / count(node_cpu_seconds_total{instance=\"$host\", mode=\"idle\"}))",
       "legendFormat": "percent"
      }
     ]
    },
    {
     "title": "Memory Used",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
     "targets": [
      {
       "expr": "1 - (node_memory_MemAvailable_bytes{instance=\"$host\"} or (node_memory_MemFree_bytes{instance=\"$host\"} + node_memory_Buffers_bytes{instance=\"$host\"} + node_memory_Cached_bytes{instance=\"$host\"})) / node_memory_MemTotal_bytes{instance=\"$host\"}"
      }
     ]
    },
    {
     "title": "Swap Used",
     "type": "singlestat",
     "description": "When the result is `False`, the swap is off.",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "((node_memory_SwapTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$node:$port\",job=~\"$job\"}) / (node_memory_SwapTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} )) * 100"
      }
     ]
    },
    {
     "title": "Load1",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "node_load1{instance=\"$host\"}"
      }
     ]
    },
    {
     "title": "Load5",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "node_load5{instance=\"$host\"}"
      }
     ]
    },
    {
     "title": "Load15",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "node_load15{instance=\"$host\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "OS",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 8 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "node_uname_info{instance=~\"$host\"}"
      }
     ]
    },
    {
     "title": "Machine",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 7, "x": 7, "y": 8 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "node_uname_info{instance=~\"$host\"}"
      }
     ]
    },
    {
     "title": "Kernel version",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 10, "x": 14, "y": 8 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "node_uname_info{instance=~\"$host\"}"
      }
     ]
    },
    {
     "title": "Interrupts",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(node_intr_total{instance=\"$host\"}[$interval]) or irate(node_intr_total{instance=\"$host\"}[5m])",
       "legendFormat": "Interrupts",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_running%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "Forks",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(node_forks_total{instance=\"$host\"}[$interval]) or irate(node_forks_total{instance=\"$host\"}[5m])",
       "legendFormat": "Forks",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_running%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "Context Switches",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(node_context_switches_total{instance=\"$host\"}[$interval]) or irate(node_context_switches_total{instance=\"$host\"}[5m])",
       "legendFormat": "Context Switches",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_running%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "sum(rate(node_cpu_seconds_total{instance=\"$host\"}[$interval])) by (mode) * 100 / count(node_cpu_seconds_total{instance=\"$host\"}) by (mode) or sum(irate(node_cpu_seconds_total{instance=\"$host\"}[5m])) by (mode) * 100 / count(node_cpu_seconds_total{instance=\"$host\"}) by (mode)",
       "legendFormat": "{{mode}}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22sum(rate(node_cpu%7Binstance%3D%5C%22%24host%5C%22%7D%5B%24interval%5D))%20by%20(mode)%20*%20100%22%2C%22range_input%22%3A%223600s%22%2C%22end_input%22%3A%222015-10-22%2015%3A27%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_memory_MemTotal_bytes{instance=\"$host\"}",
       "legendFormat": "Total",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      },
      {
       "calculatedInterval": "2s",
       "expr": "node_memory_MemTotal_bytes{instance=\"$host\"} - (node_memory_MemAvailable_bytes{instance=\"$host\"} or (node_memory_MemFree_bytes{instance=\"$host\"} + node_memory_Buffers_bytes{instance=\"$host\"} + node_memory_Cached_bytes{instance=\"$host\"}))",
       "legendFormat": "Used",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Binstance%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Binstance%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      },
      {
       "calculatedInterval": "2s",
       "expr": "node_memory_MemAvailable_bytes{instance=\"$host\"} or (node_memory_MemFree_bytes{instance=\"$host\"} + node_memory_Buffers_bytes{instance=\"$host\"} + node_memory_Cached_bytes{instance=\"$host\"})",
       "legendFormat": "Available",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "Distribution",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_memory_MemTotal_bytes{instance=\"$host\"} - (node_memory_MemFree_bytes{instance=\"$host\"} + node_memory_Buffers_bytes{instance=\"$host\"} + node_memory_Cached_bytes{instance=\"$host\"})",
       "legendFormat": "Used",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Binstance%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Binstance%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      },
      {
       "calculatedInterval": "2s",
       "expr": "node_memory_MemFree_bytes{instance=\"$host\"}",
       "legendFormat": "Free",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      },
      {
       "calculatedInterval": "2s",
       "expr": "node_memory_Buffers_bytes{instance=\"$host\"}",
       "legendFormat": "Buffers",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      },
      {
       "calculatedInterval": "2s",
       "expr": "node_memory_Cached_bytes{instance=\"$host\"}",
       "legendFormat": "Cached",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "Available Buddy Pages - Zone $buddyinfozone",
     "type": "graph",
     "description": "From /proc/buddyinfo. Low values indicate heavy memory fragmentation.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "repeat": "buddyinfozone",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_buddyinfo_blocks{instance=\"$host\",zone=\"$buddyinfozone\"}",
       "legendFormat": "Node {{node}} - Order {{size}}"
      }
     ]
    },
    {
     "title": "Active / Inactive",
     "type": "graph",
     "description": "Inactive: Recently used less memory, priority to be recycled\n\nActive: Recently used memory is not usually recycled unless absolutely necessary",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Inactive_bytes{instance=~\"$host\"}",
       "legendFormat": "Inactive"
      },
      {
       "expr": "node_memory_Active_bytes{instance=~\"$host\"}",
       "legendFormat": "Active"
      }
     ]
    },
    {
     "title": "Writeback and Dirty",
     "type": "graph",
     "description": "Writeback: Preparing to actively write back to the cache page of the hard disk\n\nWritebackTmp: Memory used to temporarily write back to the buffer\n\nDirty: The data size that needs to be written back to disk",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Writeback_bytes{instance=~\"$host\"}",
       "legendFormat": "Writeback"
      },
      {
       "expr": "node_memory_WritebackTmp_bytes{instance=~\"$host\"}",
       "legendFormat": "WritebackTmp"
      },
      {
       "expr": "node_memory_Dirty_bytes{instance=~\"$host\"}",
       "legendFormat": "Dirty"
      }
     ]
    },
    {
     "title": "Shared and Mapped",
     "type": "graph",
     "description": "Mapped: The memory occupied by a mapped page\n\nShared: The Shared memory",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Mapped_bytes{instance=~\"$host\"}",
       "legendFormat": "Mapped"
      },
      {
       "expr": "node_memory_Shmem_bytes{instance=~\"$host\"}",
       "legendFormat": "Shared"
      }
     ]
    },
    {
     "title": "Mlocked/Slab",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_memory_Mlocked_bytes{instance=~\"$host\"}",
       "legendFormat": "Mlocked"
      },
      {
       "expr": "node_memory_Slab_bytes{instance=~\"$host\"}",
       "legendFormat": "Slab"
      }
     ]
    },
    {
     "title": "KernelStack",
     "type": "graph",
     "description": "Kernel stack size (resident memory, non-recyclable)",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_KernelStack_bytes{instance=~\"$host\"}",
       "legendFormat": "KernelStack"
      }
     ]
    },
    {
     "title": "Anonymous",
     "type": "graph",
     "description": "AnonHugePages: The memory footprint of AnonHugePages\n\nAnonPages: Anonymous memory page size in the user process",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_AnonHugePages_bytes{instance=~\"$host\"}",
       "legendFormat": "AnonHugePages"
      },
      {
       "expr": "node_memory_AnonPages_bytes{instance=~\"$host\"}",
       "legendFormat": "AnonPages"
      }
     ]
    },
    {
     "title": "HugePages Size",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Hugepagesize_bytes{instance=~\"$host\"}",
       "legendFormat": "Hugepagesize"
      }
     ]
    },
    {
     "title": "HugePages Counter",
     "type": "graph",
     "description": "HugePages_Free: The total number of idle HugePages that the system currently has\n\nHugePages_Rsvd: The total number of HugePages currently retained by the system\n\nHugePages_Surp: Exceeds the number of resident HugePages set by the system\n\nHugePages: The total number of HugePages currently owned by the system",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_memory_HugePages_Free{instance=~\"$host\"}",
       "legendFormat": "HugePages_Free"
      },
      {
       "expr": "node_memory_HugePages_Rsvd{instance=~\"$host\"}",
       "legendFormat": "HugePages_Rsvd"
      },
      {
       "expr": "node_memory_HugePages_Surp{instance=~\"$host\"}",
       "legendFormat": "HugePages_Surp"
      },
      {
       "expr": "node_memory_HugePages_Total{instance=~\"$host\"}",
       "legendFormat": "HugePages"
      }
     ]
    },
    {
     "title": "Commit",
     "type": "graph",
     "description": "Committed_AS: The amount of memory that has been allocated by the current system, including the size of the memory that has been allocated but is not yet used\n\nCommitLimit: The amount of memory that can be allocated to the current system",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Committed_AS_bytes{instance=~\"$host\"}",
       "legendFormat": "Committed_AS"
      },
      {
       "expr": "node_memory_CommitLimit_bytes{instance=~\"$host\"}",
       "legendFormat": "CommitLimit"
      }
     ]
    },
    {
     "title": "Swap",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_memory_SwapTotal_bytes{instance=\"$host\"} - node_memory_SwapFree_bytes{instance=\"$host\"}",
       "legendFormat": "Used",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Binstance%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Binstance%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      },
      {
       "calculatedInterval": "2s",
       "expr": "node_memory_SwapFree_bytes{instance=\"$host\"}",
       "legendFormat": "Free",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "Swap Activity",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_vmstat_pswpin{instance=\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{instance=\"$host\"}[5m]) * 4096",
       "legendFormat": "Swap In",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Binstance%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Binstance%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      },
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_vmstat_pswpout{instance=\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{instance=\"$host\"}[5m]) * 4096",
       "legendFormat": "Swap Out",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "Page/Swap in/out",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_vmstat_pgpgin{instance=\"$host\"}[1m])",
       "legendFormat": "page in"
      },
      {
       "expr": "rate(node_vmstat_pgpgout{instance=\"$host\"}[1m])",
       "legendFormat": "page out"
      },
      {
       "expr": "rate(node_vmstat_pswpout{instance=\"$host\"}[1m])",
       "legendFormat": "swap out"
      },
      {
       "expr": "rate(node_vmstat_pswpin{instance=\"$host\"}[1m])",
       "legendFormat": "swap in"
      }
     ]
    },
    {
     "title": "Mem Fault",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_vmstat_pgmajfault{instance=\"$host\"}[1m])",
       "legendFormat": "major fault"
      },
      {
       "expr": "rate(node_vmstat_pgfault{instance=\"$host\"}[1m])",
       "legendFormat": "minor fault"
      }
     ]
    }
   ]
  },
  {
   "title": "Vmstat - Page",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pages In / Out",
     "type": "graph",
     "description": "The rate at which data is read from the hard disk to physical memory (within 5 minutes)\n\nRate at which data is written from physical memory to hard disk (within 5 minutes)",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgpgin{instance=~\"$host\"}[5m])",
       "legendFormat": "pgpgin"
      },
      {
       "expr": "irate(node_vmstat_pgpgout{instance=~\"$host\"}[5m])",
       "legendFormat": "pgpgout"
      }
     ]
    },
    {
     "title": "Pages Swap In / Out",
     "type": "graph",
     "description": "Rate at which data is loaded into memory from disk swap (5 minutes)\n\nRate at which data is dumped from memory to disk swap (within 5 minutes)",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pswpin{instance=~\"$host\"}[5m])",
       "legendFormat": "pswpin"
      },
      {
       "expr": "irate(node_vmstat_pswpout{instance=~\"$host\"}[5m])",
       "legendFormat": "Pswpout"
      }
     ]
    },
    {
     "title": "Page Operations",
     "type": "graph",
     "description": "pgdeactivate: Average number of pages activated (within 5 minutes)\n\npgfree: Average number of pages released (within 5 minutes)\n\npgactivate: Average number of pages not activated (within 5 minutes)",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgdeactivate{instance=~\"$host\"}[5m])",
       "legendFormat": "pgdeactivate"
      },
      {
       "expr": "irate(node_vmstat_pgfree{instance=~\"$host\"}[5m])",
       "legendFormat": "pgfree"
      },
      {
       "expr": "irate(node_vmstat_pgactivate{instance=~\"$host\"}[5m])",
       "legendFormat": "pgactivate"
      }
     ]
    },
    {
     "title": "Allocstall",
     "type": "graph",
     "description": "Average number of pages requested to be recycled directly (within 5 minutes)",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_allocstall{instance=\"$host\"}[5m])",
       "legendFormat": "allocstall"
      }
     ]
    },
    {
     "title": "Page Drop",
     "type": "graph",
     "description": "drop_pagecache: Average number of pages called to release the cache (within 5 minutes)\n\ndrop_slab: Average number of pages to call to release the slab cache (in 5 minutes)",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "Cells" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_drop_pagecache{instance=~\"$host\"}",
       "legendFormat": "drop_pagecache"
      },
      {
       "expr": "node_vmstat_drop_slab{instance=~\"$host\"}",
       "legendFormat": "drop_slab"
      }
     ]
    },
    {
     "title": "Page Allocation",
     "type": "graph",
     "description": "pgalloc_dma: Average number of pages allocated by DMA storage area (within 5 minutes)\n\npgalloc_dma32: Average number of pages allocated in DMA32 storage (within 5 minutes)\n\npgalloc_movable: Movable storage allocated average number of pages (within 5 minutes)\n\npgalloc_normal: Average number of pages allocated by normal storage (within 5 minutes)",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgalloc_dma{instance=~\"$host\"}[5m])",
       "legendFormat": "pgalloc_dma"
      },
      {
       "expr": "irate(node_vmstat_pgalloc_dma32{instance=~\"$host\"}[5m])",
       "legendFormat": "pgalloc_dma32"
      },
      {
       "expr": "irate(node_vmstat_pgalloc_movable{instance=~\"$host\"}[5m])",
       "legendFormat": "pgalloc_movable"
      },
      {
       "expr": "irate(node_vmstat_pgalloc_normal{instance=~\"$host\"}[5m])",
       "legendFormat": "pgalloc_normal"
      }
     ]
    }
   ]
  },
  {
   "title": "Vmstat - Numa",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Numa Allocations",
     "type": "graph",
     "description": "foreign: Plan to use other node memory but use local memory\n\nhit: Use this node memory times\n\ninterleave: The number of times the memory of this node is used in the memory used for cross-allocation\n\nlocal: The program running on this node uses the memory of this node\n\nmiss: The number of times that you plan to use this node memory to be dispatched to other nodes\n\nother: Programs running on other nodes use the memory of this node",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Allocations" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_numa_foreign{instance=~\"$host\"}[5m])",
       "legendFormat": "foreign"
      },
      {
       "expr": "irate(node_vmstat_numa_hit{instance=~\"$host\"}[5m])",
       "legendFormat": "hit"
      },
      {
       "expr": "irate(node_vmstat_numa_interleave{instance=~\"$host\"}[5m])",
       "legendFormat": "interleave"
      },
      {
       "expr": "irate(node_vmstat_numa_local{instance=~\"$host\"}[5m])",
       "legendFormat": "local"
      },
      {
       "expr": "irate(node_vmstat_numa_miss{instance=~\"$host\"}[5m])",
       "legendFormat": "miss"
      },
      {
       "expr": "irate(node_vmstat_numa_other{instance=~\"$host\"}[5m])",
       "legendFormat": "other"
      }
     ]
    },
    {
     "title": "Numa Page Migrations",
     "type": "graph",
     "description": "pages_migrated: NUMA page number\n\nPgmigrate_fail: Number of pages failed to migrate\n\nPgmigrate_success: Number of pages successfully migrated",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_numa_pages_migrated{instance=~\"$host\"}[5m])",
       "legendFormat": "pages_migrated"
      },
      {
       "expr": "irate(node_vmstat_pgmigrate_fail{instance=~\"$host\"}[5m])",
       "legendFormat": "pgmigrate_fail"
      },
      {
       "expr": "irate(node_vmstat_pgmigrate_success{instance=~\"$host\"}[5m])",
       "legendFormat": "Pgmigrate_success"
      }
     ]
    },
    {
     "title": "Numa Hints",
     "type": "graph",
     "description": "hint_faults: NUMA hint faults trapped\n\nhint_faults_local: Hinting faults to local nodes",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "Hints" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_numa_hint_faults{instance=~\"$host\"}[5m])",
       "legendFormat": "hint_faults"
      },
      {
       "expr": "irate(node_vmstat_numa_hint_faults_local{instance=~\"$host\"}[5m])",
       "legendFormat": "hint_faults_local"
      }
     ]
    },
    {
     "title": "Numa Table Updates",
     "type": "graph",
     "description": "pte_updates: NUMA page table entry updates\n\nhuge_pte_updates: NUMA huge page table entry updates",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "Updates" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_numa_pte_updates{instance=~\"$host\"}[5m])",
       "legendFormat": "pte_updates"
      },
      {
       "expr": "irate(node_vmstat_numa_huge_pte_updates{instance=~\"$host\"}[5m])",
       "legendFormat": "huge_pte_updates"
      }
     ]
    },
    {
     "title": "Numa Mem Usage",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "node_memory_numa_MemUsed{instance=\"$host\"} / node_memory_numa_MemTotal{instance=\"$host\"}",
       "legendFormat": "Numa node: {{ node }}"
      }
     ]
    },
    {
     "title": "Numa Mem Free",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_numa_MemFree{instance=\"$host\"}",
       "legendFormat": "Numa node: {{ node }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Vmstat - THP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "THP Splits",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Splits" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_thp_split{instance=~\"$host\"}[5m])",
       "legendFormat": "split"
      }
     ]
    },
    {
     "title": "THP Allocations",
     "type": "graph",
     "description": "collapse_alloc: Transparent huge page collapse allocations\n\ncollapse_alloc_failed: Transparent huge page collapse allocation failures\n\nzero_page_alloc: Transparent huge page zeroed page allocations\n\nzero_page_alloc_failed: Transparent huge page zeroed page allocation failures\n\nfault_alloc: Transparent huge page fault allocations\n\nfault_fallback: Transparent huge page fault fallbacks",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short", "label": "Allocations" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_thp_collapse_alloc{instance=~\"$host\"}[5m])",
       "legendFormat": "collapse_alloc"
      },
      {
       "expr": "irate(node_vmstat_thp_collapse_alloc_failed{instance=~\"$host\"}[5m])",
       "legendFormat": "collapse_alloc_failed"
      },
      {
       "expr": "irate(node_vmstat_thp_zero_page_alloc{instance=~\"$host\"}[5m])",
       "legendFormat": "zero_page_alloc"
      },
      {
       "expr": "irate(node_vmstat_thp_zero_page_alloc_failed{instance=~\"$host\"}[5m])",
       "legendFormat": "zero_page_alloc_failed"
      },
      {
       "expr": "irate(node_vmstat_thp_fault_alloc{instance=~\"$host\"}[5m])",
       "legendFormat": "fault_alloc"
      },
      {
       "expr": "irate(node_vmstat_thp_fault_fallback{instance=~\"$host\"}[5m])",
       "legendFormat": "fault_fallback"
      }
     ]
    }
   ]
  },
  {
   "title": "Vmstat - Compact",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Compact Status",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Compactions" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_compact_fail{instance=~\"$host\"}[5m])",
       "legendFormat": "fail"
      },
      {
       "expr": "irate(node_vmstat_compact_success{instance=~\"$host\"}[5m])",
       "legendFormat": "success"
      }
     ]
    },
    {
     "title": "Compact Stall",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short", "label": "Compactions" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_compact_stall{instance=~\"$host\"}[5m])",
       "legendFormat": "Compact_stall"
      }
     ]
    },
    {
     "title": "Compact Isolated",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_compact_isolated{instance=~\"$host\"}[5m])",
       "legendFormat": "isolated"
      }
     ]
    },
    {
     "title": "Compact Free Scanned",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_compact_free_scanned{instance=~\"$host\"}[5m])",
       "legendFormat": "free_scanned"
      }
     ]
    },
    {
     "title": "Compact Migrate Scanned",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_compact_migrate_scanned{instance=~\"$host\"}[5m])",
       "legendFormat": "migrate_scanned"
      }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load: 1m",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "node_load1{instance=\"$host\"}",
       "legendFormat": "Load 1m",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_load1%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%223601s%22%2C%22end_input%22%3A%222015-10-22%2015%3A27%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "Load: 5m",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "node_load5{instance=\"$host\"}",
       "legendFormat": "Load 5m",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_load5%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%223600s%22%2C%22end_input%22%3A%222015-10-22%2015%3A27%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "Load: 15m",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "node_load15{instance=\"$host\"}",
       "legendFormat": "Load 15m",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_load15%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%223600s%22%2C%22end_input%22%3A%222015-10-22%2015%3A27%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Disk Size",
     "type": "table",
     "gridPos": { "h": 4, "w": 16, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=\"$host\",device=~'^/.*'}",
       "legendFormat": "Disk Size: {{ device }} {{ fstype }} {{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Disk State",
     "type": "table",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 7 },
     "targets": [
      {
       "expr": "node_filesystem_readonly{instance=\"$host\", device=~\"/.*\"}"
      }
     ]
    },
    {
     "title": "Disk Space Utilization",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - node_filesystem_avail_bytes{instance=\"$host\", device=~'^/.*'} / node_filesystem_size_bytes{instance=\"$host\", device=~'^/.*'}",
       "legendFormat": "{{ device }} - {{ fstype }} - {{ mountpoint }}"
      }
     ]
    },
    {
     "title": "I/O Util",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_disk_io_time_seconds_total{instance=\"$host\"}[$interval]) or irate(node_disk_io_time_seconds_total{instance=\"$host\"}[1m])",
       "legendFormat": "{{ device }}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Binstance%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Binstance%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "IOPs",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_disk_reads_completed_total{instance=~\"$host\"}[5m]) + rate(node_disk_writes_completed_total{instance=~\"$host\"}[5m]))",
       "legendFormat": "IOPs"
      }
     ]
    },
    {
     "title": "Disk Write Latency (ms)",
     "type": "graph",
     "description": "DISK seconds Read/ Write Latency.\n- Critical:\n  - Recommended performance value is < 10ms as avg value of the Avg Disk sec/Read,Write.\n  - Critical value of the Avg Disk sec/Read,Write is > 50ms, should not exceed this value.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(rate(node_disk_write_time_seconds_total{instance=~\"$host\"}[5m])/ rate(node_disk_writes_completed_total{instance=~\"$host\"}[5m]))",
       "legendFormat": "Disk Write Latency: [{{ device }}]"
      }
     ]
    },
    {
     "title": "Disk Read Latency (ms)",
     "type": "graph",
     "description": "Disk seconds Read Latency.\n- Critical:\n  - Recommended performance value is < 10ms as avg value of the Avg Disk sec/Read,Write.\n  - Critical value of the Avg Disk sec/Read,Write is > 50ms, should not exceed this value.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(rate(node_disk_read_time_seconds_total{instance=~\"$host\"}[5m])/ rate(node_disk_reads_completed_total{instance=~\"$host\"}[5m]))",
       "legendFormat": "Disk Read Latency: [{{ device }}]"
      }
     ]
    },
    {
     "title": "Disk Throughput",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=~\"$host\"}[5m]) + irate(node_disk_written_bytes_total{instance=~\"$host\"}[5m])",
       "legendFormat": "Disk Troughput: [{{ device }}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystem Device Error",
     "type": "graph",
     "description": "Whether an error occurred while getting statistics for the given device.\n> A value > 0 Means that there are some problems with that device.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_device_error{instance=~\"$host\"} ",
       "legendFormat": "Filesystem Device Error: {{fstype}} {{device}} {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Filesystem Space Used",
     "type": "graph",
     "description": "Filesystem used space.\n> If is > 80% then is Critical.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "((node_filesystem_size_bytes{instance=~\"$host\"} - node_filesystem_avail_bytes{instance=~\"$host\"}) / node_filesystem_size_bytes{instance=~\"$host\"}) * 100",
       "legendFormat": "Filesystem Space Used:  {{fstype}} {{device}} {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Filesystem Inodes Used",
     "type": "graph",
     "description": "Filesystem used file nodes.\n> If is > 85% the is Critical.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_files_free{instance=~\"$host\"} / node_filesystem_files{instance=~\"$host\"}",
       "legendFormat": "Filesystem Inodes:  {{fstype}} {{device}} {{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Descriptors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Allocated File Descriptor",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_filefd_allocated{instance=\"$host\"}",
       "legendFormat": "Allocated File Descriptor"
      }
     ]
    },
    {
     "title": "Maximum File Descriptor",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_filefd_maximum{instance=\"$host\"}",
       "legendFormat": "Maximum File Descriptor"
      }
     ]
    },
    {
     "title": "File Descriptors Used",
     "type": "graph",
     "description": "A file descriptor is a data structure used by a program to get a handle on a file, the most well know being 0,1,2 for standard in, standard out, and standard error.\n\nThe maximum number of file handles denotes the maximum number of open files on a Linux system.\n\nThe kernel dynamically allocates file handles whenever a file handle is requested by an application but the kernel does not free these file handles when they are released by the application. The kernel recycles these file handles instead. This means that over time the total number of allocated file handles will increase even though the number of currently used file handles may be low.\n\n>$ cat /proc/sys/fs/file-nr\n\n    1376    0       785623\n\n- 1376: total allocated file descriptors (the number of file descriptors allocated since boot)\n- 0: total free allocated file descriptors\n- 785623: maximum open file descriptors [the maximum file handles that can be allocated (also found in /proc/sys/fs/file-max)]\n\n1376 - 0 = 1376 (being used)",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(node_filefd_allocated{instance=~\"$host\"} / node_filefd_maximum{instance=~\"$host\"}) * 100",
       "legendFormat": "File Descriptors Used"
      }
     ]
    },
    {
     "title": "Process Open Files Used",
     "type": "graph",
     "description": "Open Files Limits.\n- Critical:\n   - If > 85% then there is High Usage.\n\nprocess_open_fds\t\n>Number of open file descriptors.\t\n\nprocess_max_fds\t\n> Maximum number of open file descriptors.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(process_open_fds{instance=~\"$host\"} / process_max_fds{instance=~\"$host\"}) * 100",
       "legendFormat": "Open Files Used"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Interface State",
     "type": "graph",
     "description": "Thresholds:\n- Critical if state = DOWN (0)",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "node_network_up{instance=~\"$host\",interface!=\"lo\"}",
       "legendFormat": "Interface:  [{{interface}}] {{operstate}}"
      }
     ]
    },
    {
     "title": "Network IN/OUT Drops",
     "type": "graph",
     "description": "Network Drops.\n- Critical:\n   - If  is > 0 then are Drops on that interface (IN/OUT) and is not ok.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_drop_total{instance=~\"$host\",device!=\"lo\"}[5m]) ",
       "legendFormat": "IN: {{device}}"
      },
      {
       "expr": "rate(node_network_transmit_drop_total{instance=~\"$host\",device!=\"lo\"}[5m]) ",
       "legendFormat": "OUT: {{device}}"
      }
     ]
    },
    {
     "title": "Network IN/OUT Errors",
     "type": "graph",
     "description": "Network Errors on IN/OUT.\n- Critical:\n  - If Errors > 0 then there are some problems on that interface.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_errs_total{instance=~\"$host\",device!=\"lo\"}[5m]) ",
       "legendFormat": "IN: {{device}}"
      },
      {
       "expr": "rate(node_network_transmit_errs_total{instance=~\"$host\",device!=\"lo\"}[5m]) ",
       "legendFormat": "OUT: {{device}}"
      }
     ]
    },
    {
     "title": "Network IN/OUT Traffic",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_network_receive_bytes_total{instance=\"$host\", device!=\"lo\"}[$interval]) or irate(node_network_receive_bytes_total{instance=\"$host\", device!=\"lo\"}[5m])",
       "legendFormat": "Inbound: {{ device }}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      },
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_network_transmit_bytes_total{instance=\"$host\", device!=\"lo\"}[$interval]) or irate(node_network_transmit_bytes_total{instance=\"$host\", device!=\"lo\"}[5m])",
       "legendFormat": "Outbound: {{ device }}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Binstance%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Binstance%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "Network IN/OUT Packets",
     "type": "graph",
     "description": "Network Packets for IN/OUT.\n- Critical:\n   - If  is = 0 for IN/OUT.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_network_receive_packets_total{instance=~\"$host\",device!=\"lo\"}[$interval]) or irate(node_network_receive_packets_total{instance=~\"$host\",device!=\"lo\"}[5m])",
       "legendFormat": "Inbound: {{ device }}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      },
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_network_transmit_packets_total{instance=~\"$host\",device!=\"lo\"}[$interval]) or irate(node_network_transmit_packets_total{instance=~\"$host\",device!=\"lo\"}[5m])",
       "legendFormat": "Outbound: {{ device }}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Binstance%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Binstance%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "Network Interface Speed",
     "type": "graph",
     "description": "- node_network_transmit_queue_length = transmit_queue_length value of /sys/class/net/<iface>.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "node_network_transmit_queue_length{instance=~\"$host\",interface!=\"lo\"}",
       "legendFormat": "MTU:  [{{interface}}]"
      }
     ]
    },
    {
     "title": "Network Utilization Hourly",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "sum(increase(node_network_receive_bytes_total{instance=\"$host\", device!=\"lo\"}[1h]))",
       "legendFormat": "Received",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Binstance%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Binstance%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      },
      {
       "calculatedInterval": "2s",
       "expr": "sum(increase(node_network_transmit_bytes_total{instance=\"$host\", device!=\"lo\"}[1h]))",
       "legendFormat": "Sent",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Binstance%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Binstance%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    }
   ]
  },
  {
   "title": "TCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP In Use",
     "type": "graph",
     "description": "Number of TCP sockets in state inuse.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_TCP_inuse{instance=\"$host\"}",
       "legendFormat": "TCP In Use"
      }
     ]
    },
    {
     "title": "Segments retransmitted",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(node_netstat_Tcp_RetransSegs{instance=~\"$host\"}[$interval]) or irate(node_netstat_Tcp_RetransSegs{instance=~\"$host\"}[5m])",
       "legendFormat": "RetransSegs - Segments retransmitted"
      }
     ]
    },
    {
     "title": "TCP Connections",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{instance=~\"$host\"}",
       "legendFormat": "CurrEstab"
      }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "node_procs_running{instance=\"$host\"}",
       "legendFormat": "Processes in runnable state",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_running%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      },
      {
       "calculatedInterval": "2m",
       "expr": "node_procs_blocked{instance=\"$host\"}",
       "legendFormat": "Processes blocked waiting for I/O to complete",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_blocked%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    }
   ]
  }
 ]
}