{
 "title": "Test-Cluster-PD",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(pd_cluster_status, instance)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(pd_cluster_status{instance=\"$instance\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "PD role",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(delta(pd_tso_events{type=\"save\",instance=\"$instance\"}[1m]))"
      }
     ]
    },
    {
     "title": "Storage capacity",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(pd_cluster_status{instance=\"$instance\",namespace=~\"$namespace\",type=\"storage_capacity\"})"
      }
     ]
    },
    {
     "title": "Current storage size",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(pd_cluster_status{instance=\"$instance\",namespace=~\"$namespace\",type=\"storage_size\"})"
      }
     ]
    },
    {
     "title": "Current storage used",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(pd_cluster_status{instance=\"$instance\",namespace=~\"$namespace\",type=\"storage_size\"}) / sum(pd_cluster_status{instance=\"$instance\",namespace=~\"$namespace\",type=\"storage_capacity\"})"
      }
     ]
    },
    {
     "title": "Normal stores",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(pd_cluster_status{instance=\"$instance\", namespace=~\"$namespace\", type=\"store_up_count\"})"
      }
     ]
    },
    {
     "title": "Number of Regions",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(pd_cluster_status{instance=\"$instance\",namespace=~\"$namespace\",type=\"leader_count\"})"
      }
     ]
    },
    {
     "title": "PD scheduler config",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
     "targets": [
      { "expr": "pd_config_status", "legendFormat": "{{type}}-{{namespace}}" }
     ]
    },
    {
     "title": "Region label isolation level",
     "type": "table",
     "gridPos": { "h": 7, "w": 5, "x": 6, "y": 7 },
     "targets": [
      {
       "expr": "pd_regions_label_level{instance=\"$instance\"}",
       "legendFormat": "label_{{type}}"
      }
     ]
    },
    {
     "title": "Label distribution",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 11, "y": 7 },
     "targets": [
      { "expr": "pd_cluster_placement_status", "legendFormat": "{{name}}" }
     ]
    },
    {
     "title": "Abnormal stores",
     "type": "table",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 7 },
     "targets": [
      {
       "expr": "sum(pd_cluster_status{instance=\"$instance\", namespace=~\"$namespace\",type=\"store_disconnected_count\"})",
       "legendFormat": "Disconnect Stores"
      },
      {
       "expr": "sum(pd_cluster_status{instance=\"$instance\", namespace=~\"$namespace\",type=\"store_unhealth_count\"})",
       "legendFormat": "Unhealth Stores"
      },
      {
       "expr": "sum(pd_cluster_status{instance=\"$instance\", namespace=~\"$namespace\",type=\"store_low_space_count\"})",
       "legendFormat": "LowSpace Stores"
      },
      {
       "expr": "sum(pd_cluster_status{instance=\"$instance\", namespace=~\"$namespace\",type=\"store_down_count\"})",
       "legendFormat": "Down Stores"
      },
      {
       "expr": "sum(pd_cluster_status{instance=\"$instance\", namespace=~\"$namespace\",type=\"store_offline_count\"})",
       "legendFormat": "Offline Stores"
      },
      {
       "expr": "sum(pd_cluster_status{instance=\"$instance\", namespace=~\"$namespace\",type=\"store_tombstone_count\"})",
       "legendFormat": "Tombstone Stores"
      }
     ]
    },
    {
     "title": "pd_cluster_metadata",
     "type": "table",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "pd_cluster_metadata{instance=\"$instance\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Current peer count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 4, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(pd_cluster_status{instance=\"$instance\", namespace=~\"$namespace\", type=\"region_count\"})",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Region health",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_regions_status{instance=\"$instance\"}",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Operator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Schedule operator create",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_operators_count{instance=\"$instance\", event=\"create\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Schedule operator check",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_operators_count{instance=\"$instance\", event=\"check\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Schedule operator finish",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_operators_count{instance=\"$instance\", event=\"finish\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Schedule operator timeout",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_operators_count{instance=\"$instance\", event=\"timeout\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Schedule operator replaced or canceled",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_operators_count{instance=\"$instance\", event=\"canceled\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(delta(pd_schedule_operators_count{instance=\"$instance\", event=\"replaced\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Schedule operators count by state",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_operators_count{instance=\"$instance\"}[1m])) by (event)",
       "legendFormat": "{{event}}"
      }
     ]
    },
    {
     "title": "99% Operator finish duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_schedule_finish_operators_duration_seconds_bucket[5m])) by (type, le))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "50% Operator finish duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(pd_schedule_finish_operators_duration_seconds_bucket[5m])) by (type, le))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "99% Operator step finish duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_schedule_finish_operator_steps_duration_seconds_bucket[5m])) by (type, le))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "50% Operator step finish duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(pd_schedule_finish_operator_steps_duration_seconds_bucket[5m])) by (type, le))",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Statistics - balance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Store capacity",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{instance=\"$instance\", namespace=~\"$namespace\", type=\"store_capacity\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store available",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "{instance=\"$instance\", namespace=~\"$namespace\", type=\"store_available\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store used",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{instance=\"$instance\", namespace=~\"$namespace\", type=\"store_used\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store available ratio",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(pd_scheduler_store_status{instance=\"$instance\", namespace=~\"$namespace\", type=\"store_available\"}) by (address, store) / sum(pd_scheduler_store_status{instance=\"$instance\", namespace=~\"$namespace\", type=\"store_capacity\"}) by (address, store)",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Size amplification",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pd_scheduler_store_status{instance=\"$instance\", namespace=~\"$namespace\", type=\"region_size\"}) by (address, store) / sum(pd_scheduler_store_status{instance=\"$instance\", namespace=~\"$namespace\", type=\"store_used\"}) by (address, store) * 2^20",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store Region score",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{instance=\"$instance\", namespace=~\"$namespace\", type=\"region_score\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store leader score",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{instance=\"$instance\", namespace=~\"$namespace\", type=\"leader_score\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store Region size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{instance=\"$instance\", namespace=~\"$namespace\", type=\"region_size\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store leader size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{instance=\"$instance\", namespace=~\"$namespace\", type=\"leader_size\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store Region count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{instance=\"$instance\", namespace=~\"$namespace\", type=\"region_count\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store leader count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{instance=\"$instance\", namespace=~\"$namespace\", type=\"leader_count\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Statistics - hotspot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hot write Region's leader distribution",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_hotspot_status{instance=\"$instance\",type=\"hot_write_region_as_leader\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Hot write Region's peer distribution",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_hotspot_status{instance=\"$instance\",type=\"hot_write_region_as_peer\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Hot write Region's leader written bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "pd_hotspot_status{instance=\"$instance\",type=\"total_written_bytes_as_leader\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Hot Region's peer written bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 90 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "pd_hotspot_status{instance=\"$instance\",type=\"total_written_bytes_as_peer\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Hot read Region's leader distribution",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 97 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_hotspot_status{instance=\"$instance\",type=\"hot_read_region_as_leader\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Hot read Region's leader read bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 97 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "pd_hotspot_status{instance=\"$instance\",type=\"total_read_bytes_as_leader\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store write rate bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 104 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{type=\"store_write_rate_bytes\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store read rate bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 104 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{type=\"store_read_rate_bytes\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store write rate keys",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 111 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{type=\"store_write_rate_keys\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store read rate keys",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 111 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{type=\"store_read_rate_keys\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scheduler is running",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 112 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_status{type=\"allow\",instance=\"$instance\"}",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Balance leader movement",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "- sum(delta(pd_scheduler_balance_leader{address=~\".*out\",instance=\"$instance\", type=\"move_leader\"}[30s])) by (address, store)",
       "legendFormat": "store-{{store}}"
      },
      {
       "expr": "sum(delta(pd_scheduler_balance_leader{address=~\".*in\",instance=\"$instance\", type=\"move_leader\"}[30s])) by (address, store)",
       "legendFormat": "store-{{store}}"
      }
     ]
    },
    {
     "title": "Balance Region movement",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "-sum(delta(pd_scheduler_balance_region{address=~\".*out\",instance=\"$instance\", type=\"move_peer\"}[1m])) by (address, store)",
       "legendFormat": "store-{{store}}"
      },
      {
       "expr": "sum(delta(pd_scheduler_balance_region{address=~\".*in\",instance=\"$instance\", type=\"move_peer\"}[1m])) by (address, store)",
       "legendFormat": "store-{{store}}"
      }
     ]
    },
    {
     "title": "Balance leader event",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_balance_leader{instance=\"$instance\", type!=\"move_leader\"}[30s])) by (type, address, store)",
       "legendFormat": "{{type}}_store-{{store}}"
      }
     ]
    },
    {
     "title": "Balance Region event",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_balance_region{instance=\"$instance\", type!=\"move_peer\"}[30s])) by (type, address, store)",
       "legendFormat": "{{type}}_store-{{store}}"
      }
     ]
    },
    {
     "title": "Balance leader scheduler",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_event_count{instance=\"$instance\", type=\"balance-leader-scheduler\"}[5m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Balance Region scheduler",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_event_count{instance=\"$instance\", type=\"balance-region-scheduler\"}[5m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Namespace checker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 144 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_checker_event_count{instance=\"$instance\", type=\"namespace_checker\"}[1m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Replica checker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 144 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_checker_event_count{instance=\"$instance\", type=\"replica_checker\"}[1m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Region merge checker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 144 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_checker_event_count{instance=\"$instance\", type=\"merge_checker\"}[1m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Filter target",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_filter{action=\"filter-target\"}[1m])) by (store,type)",
       "legendFormat": "{{store}}-{{type}}"
      }
     ]
    },
    {
     "title": "Filter source",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_filter{action=\"filter-source\"}[1m])) by (store,type)",
       "legendFormat": "{{store}}-{{type}}"
      }
     ]
    },
    {
     "title": "Balance Direction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_balance_region{instance=\"$instance\", type=\"direction\"}[1m])) by (store)",
       "legendFormat": "{{store}}"
      }
     ]
    },
    {
     "title": "Store Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "pd_schedule_store_limit{type=\"available\"}",
       "legendFormat": "{{store}}-avaliable"
      },
      {
       "expr": "pd_schedule_store_limit{type=\"take\"}",
       "legendFormat": "{{store}}-take"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Completed commands rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handling_seconds_count{instance=\"$instance\"}[1m])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "99% Completed commands duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{instance=\"$instance\"}[5m])) by (grpc_method, le))",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "etcd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Handle transactions count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 162 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_txn_handle_txns_duration_seconds_count[5m])) by (instance, result)",
       "legendFormat": "{{instance}} : {{result}}"
      }
     ]
    },
    {
     "title": "99% Handle transactions duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 170 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_txn_handle_txns_duration_seconds_bucket[5m])) by (instance, result, le))",
       "legendFormat": "{{instance}} {{result}}"
      }
     ]
    },
    {
     "title": "99% WAL fsync duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 170 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket[5m])) by (instance, le))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "99% Peer round trip time seconds",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 178 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(etcd_network_peer_round_trip_time_seconds_bucket[5m])) by (instance, To, le))",
       "legendFormat": "{{instance}} - {{To}}"
      }
     ]
    },
    {
     "title": "etcd disk wal fsync rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 178 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "delta(etcd_disk_wal_fsync_duration_seconds_count[1m])",
       "legendFormat": "{{instance}} etch disk wal fsync rate"
      }
     ]
    },
    {
     "title": "Raft term",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 186 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pd_server_etcd_state{type=\"term\"}",
       "legendFormat": "{{instance}} - {{job}}"
      }
     ]
    },
    {
     "title": "Raft committed index",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 186 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pd_server_etcd_state{type=\"committedIndex\"}",
       "legendFormat": "{{instance}} - {{job}}"
      }
     ]
    },
    {
     "title": "Raft applied index",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 186 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pd_server_etcd_state{type=\"appliedIndex\"}",
       "legendFormat": "{{instance}} - {{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TiDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Handle requests count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_client_request_handle_requests_duration_seconds_count[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Handle requests duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.98, sum(rate(pd_client_request_handle_requests_duration_seconds_bucket[30s])) by (type, le))",
       "legendFormat": "{{type}} 98th percentile"
      },
      {
       "expr": "avg(rate(pd_client_request_handle_requests_duration_seconds_sum[30s])) by (type) /  avg(rate(pd_client_request_handle_requests_duration_seconds_count[30s])) by (type)",
       "legendFormat": "{{type}} average"
      }
     ]
    }
   ]
  },
  {
   "title": "Heartbeat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "99% Region heartbeat latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "round(histogram_quantile(0.99, sum(rate(pd_scheduler_region_heartbeat_latency_seconds_bucket[5m])) by (address, store, le)), 1000)",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Region schedule push",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_scheduler_region_heartbeat{type=\"push\",instance=\"$instance\"}[5m])*60) by (address, store, status)",
       "legendFormat": "{{address}}-{{status}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Region heartbeat report",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_region_heartbeat{instance=\"$instance\", type=\"report\", status=\"ok\"}[1m])) by (address, store)",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Region heartbeat report active",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_region_heartbeat{instance=\"$instance\", type=\"report\", status=\"bind\"}[1m])) by (address, store)",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Region heartbeat report error",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_region_heartbeat{instance=\"$instance\", type=\"report\", status=\"err\"}[1m])) by (address, store)",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Region storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Syncer index",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 213 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pd_region_syncer_status{type=\"sync_index\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "history last index",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 213 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pd_region_syncer_status{type=\"last_index\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}