{
 "title": "Query Summary",
 "panels": [
  {
   "title": "Duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "999"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "80"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tidb_server_query_total[1m])) by (result)",
     "legendFormat": "query {{result}}"
    }
   ]
  },
  {
   "title": "Statement OPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tidb_executor_statement_total[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "QPS By Instance",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tidb_server_query_total[1m])",
     "legendFormat": "{{instance}} {{type}} {{result}}"
    }
   ]
  },
  {
   "title": "Failed Query OPM",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(tidb_server_execute_error_total[1m])) by (type, instance)",
     "legendFormat": " {{type}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Slow query",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(tidb_server_slow_query_process_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "all_proc"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(tidb_server_slow_query_cop_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "all_cop_proc"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(tidb_server_slow_query_wait_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "all_cop_wait"
    }
   ]
  }
 ]
}
{
 "title": "Query Detail",
 "panels": [
  {
   "title": "Duration 80 By Instance",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Duration 95 By Instance",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Duration 99 By Instance",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Duration 999 By Instance",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed Query OPM Detail",
   "type": "graph",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(tidb_server_execute_error_total[1m])",
     "legendFormat": "{{type}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Internal SQL OPS",
   "type": "graph",
   "description": "The internal SQL is used by TiDB itself.",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tidb_session_restricted_sql_total[30s]))"
    }
   ]
  }
 ]
}
{
 "title": "Server",
 "panels": [
  {
   "title": "Connection Count",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tidb_server_connections", "legendFormat": "{{instance}}" },
    { "expr": "sum(tidb_server_connections)", "legendFormat": "total" }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"tidb.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutine Count",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " go_goroutines{job=~\"tidb.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Events OPM",
   "type": "graph",
   "description": "TiDB Server events.",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(tidb_server_event_total[10m])",
     "legendFormat": "{{instance}}-{{type}}"
    }
   ]
  },
  {
   "title": "Uncommon Error OPM",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(tidb_server_panic_total[1m])",
     "legendFormat": "panic-{{instance}}"
    },
    {
     "expr": "increase(tidb_server_critical_error_total[1m])",
     "legendFormat": "critical-{{instance}}"
    }
   ]
  },
  {
   "title": "Keep Alive OPM",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(tidb_monitor_keep_alive_total[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Get Token Duration",
   "type": "graph",
   "description": "Duration (us) for getting token, it should be small until concurrency limit is reached.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tidb_server_get_token_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "99"
    }
   ]
  }
 ]
}
{
 "title": "Transaction",
 "panels": [
  {
   "title": "Transaction OPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tidb_session_transaction_total[1m])) by (type, sql_type)",
     "legendFormat": "{{type}}-{{sql_type}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tidb_session_transaction_duration_seconds_bucket[1m])) by (le, sql_type))",
     "legendFormat": "99-{{sql_type}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(tidb_session_transaction_duration_seconds_bucket[1m])) by (le, sql_type))",
     "legendFormat": "95-{{sql_type}}"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(tidb_session_transaction_duration_seconds_bucket[1m])) by (le, sql_type))",
     "legendFormat": "80-{{sql_type}}"
    }
   ]
  },
  {
   "title": "Transaction Statement Num",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tidb_session_transaction_statement_num_bucket[30s])) by (le, sql_type))",
     "legendFormat": "99-{{sql_type}}"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(tidb_session_transaction_statement_num_bucket[30s])) by (le, sql_type))",
     "legendFormat": "80-{{sql_type}}"
    }
   ]
  },
  {
   "title": "Session Retry Error OPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tidb_session_retry_error_total[30s])) by (type, sql_type)",
     "legendFormat": "{{type}}-{{sql_type}}"
    }
   ]
  },
  {
   "title": "Transaction Retry Num",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1.0, sum(rate(tidb_session_retry_num_bucket[30s])) by (le))",
     "legendFormat": "100"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tidb_session_retry_num_bucket[30s])) by (le))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(tidb_session_retry_num_bucket[30s])) by (le))",
     "legendFormat": "90"
    }
   ]
  }
 ]
}
{
 "title": "Executor",
 "panels": [
  {
   "title": "Expensive Executors OPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tidb_executor_expensive_total[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Queries Using Plan Cache OPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tidb_server_plan_cache_total[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}
{
 "title": "Distsql",
 "panels": [
  {
   "title": "Distsql Duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(tidb_distsql_handle_query_duration_seconds_bucket[1m])) by (le, type))",
     "legendFormat": "999-{{type}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tidb_distsql_handle_query_duration_seconds_bucket[1m])) by (le, type))",
     "legendFormat": "99-{{type}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(tidb_distsql_handle_query_duration_seconds_bucket[1m])) by (le, type))",
     "legendFormat": "90-{{type}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(tidb_distsql_handle_query_duration_seconds_bucket[1m])) by (le, type))",
     "legendFormat": "50-{{type}}"
    }
   ]
  },
  {
   "title": "Distsql QPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tidb_distsql_handle_query_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Distsql Partial QPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tidb_distsql_scan_keys_partial_num_count[1m]))"
    }
   ]
  },
  {
   "title": "Scan Keys Num",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(tidb_distsql_scan_keys_num_bucket[1m])) by (le))",
     "legendFormat": "100"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(tidb_distsql_scan_keys_num_bucket[1m])) by (le))",
     "legendFormat": "90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(tidb_distsql_scan_keys_num_bucket[1m])) by (le))",
     "legendFormat": "50"
    }
   ]
  },
  {
   "title": "Scan Keys Partial Num",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(tidb_distsql_scan_keys_partial_num_bucket[1m])) by (le))",
     "legendFormat": "100"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(tidb_distsql_scan_keys_partial_num_bucket[1m])) by (le))",
     "legendFormat": "90"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(tidb_distsql_scan_keys_partial_num_bucket[1m])) by (le))",
     "legendFormat": "50"
    }
   ]
  },
  {
   "title": "Partial Num",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(tidb_distsql_partial_num_bucket[1m])) by (le))",
     "legendFormat": "100"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(tidb_distsql_partial_num_bucket[1m])) by (le))",
     "legendFormat": "90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(tidb_distsql_partial_num_bucket[1m])) by (le))",
     "legendFormat": "50"
    }
   ]
  },
  {
   "title": "Coprocessor Seconds 999",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(tidb_tikvclient_cop_duration_seconds_bucket[1m])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}
{
 "title": "KV Errors",
 "panels": [
  {
   "title": "KV Retry Duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(tidb_tikvclient_backoff_seconds_bucket[1m])) by (le))",
     "legendFormat": "9999"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tidb_tikvclient_backoff_seconds_bucket[1m])) by (le))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(tidb_tikvclient_backoff_seconds_bucket[1m])) by (le))",
     "legendFormat": "80"
    }
   ]
  },
  {
   "title": "TiClient Region Error OPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tidb_tikvclient_region_err_total[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "KV Backoff OPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tidb_tikvclient_backoff_total[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Lock Resolve OPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tidb_tikvclient_lock_resolver_actions_total[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Other Errors OPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tidb_tikvclient_lock_cleanup_task_total[1m])) by (type)",
     "legendFormat": "cleanup_secondary_failure_{{type}}"
    },
    {
     "expr": "sum(rate(tidb_tikvclient_load_safepoint_total{type=\"fail\"}[1m]))",
     "legendFormat": "load_safepoint_failure"
    }
   ]
  }
 ]
}
{
 "title": "KV Duration",
 "panels": [
  {
   "title": "KV Request Duration 999 by store",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(tidb_tikvclient_request_seconds_bucket{type!=\"GC\"}[1m])) by (le, store))",
     "legendFormat": "store-{{store}}"
    }
   ]
  },
  {
   "title": "KV Request Duration 999 by type",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(tidb_tikvclient_request_seconds_bucket{type!=\"GC\"}[1m])) by (le,type))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "KV Cmd Duration 9999",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(tidb_tikvclient_txn_cmd_duration_seconds_bucket[1m])) by (le, type))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "KV Cmd Duration 99",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tidb_tikvclient_txn_cmd_duration_seconds_bucket[1m])) by (le, type))",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}
{
 "title": "KV Count",
 "panels": [
  {
   "title": "KV Cmd OPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tidb_tikvclient_txn_cmd_duration_seconds_count[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "KV Txn OPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tidb_tikvclient_txn_total[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Txn Regions Num 90",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(tidb_tikvclient_txn_regions_num_bucket[1m])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Txn Write Size Bytes 100",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(tidb_tikvclient_txn_write_size_bytes_bucket[1m])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Txn Write KV Num 100",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(tidb_tikvclient_txn_write_kv_num_bucket[1m])) by (le, instance))",
     "legendFormat": "100 {{instance}}"
    }
   ]
  },
  {
   "title": "Load Safepoint OPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tidb_tikvclient_load_safepoint_total{type=\"ok\"}[1m]))"
    }
   ]
  }
 ]
}
{
 "title": "PD Client",
 "panels": [
  {
   "title": "PD Client CMD OPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pd_client_cmd_handle_cmds_duration_seconds_count{type!=\"tso\"}[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "PD Client CMD Duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(pd_client_cmd_handle_cmds_duration_seconds_bucket{type!=\"tso\"}[1m])) by (le, type))",
     "legendFormat": "999-{{type}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(pd_client_cmd_handle_cmds_duration_seconds_bucket{type!=\"tso\"}[1m])) by (le, type))",
     "legendFormat": "99-{{type}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(pd_client_cmd_handle_cmds_duration_seconds_bucket{type!=\"tso\"}[1m])) by (le, type))",
     "legendFormat": "90-{{type}}"
    }
   ]
  },
  {
   "title": "PD Client CMD Fail OPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pd_client_cmd_handle_failed_cmds_duration_seconds_count[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "PD TSO OPS",
   "type": "graph",
   "description": "The duration of a client calling GetTSAsync until received the TS result.",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pd_client_cmd_handle_cmds_duration_seconds_count{type=\"tso\"}[1m]))",
     "legendFormat": "cmd"
    },
    {
     "expr": "sum(rate(pd_client_request_handle_requests_duration_seconds_count{type=\"tso\"}[1m]))",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "PD TSO Wait Duration",
   "type": "graph",
   "description": "The duration of a client calling GetTSAsync until received the TS result.",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(pd_client_cmd_handle_cmds_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
     "legendFormat": "999"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(pd_client_cmd_handle_cmds_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(pd_client_cmd_handle_cmds_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
     "legendFormat": "90"
    }
   ]
  },
  {
   "title": "PD TSO RPC Duration",
   "type": "graph",
   "description": "The duration of a client sending TSO request until received the response.",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(pd_client_request_handle_requests_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
     "legendFormat": "999"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(pd_client_request_handle_requests_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(pd_client_request_handle_requests_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
     "legendFormat": "90"
    }
   ]
  }
 ]
}
{
 "title": "Schema Load",
 "panels": [
  {
   "title": "Load Schema Duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tidb_domain_load_schema_duration_seconds_bucket[1m])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Load Schema OPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tidb_domain_load_schema_total[1m])) by (instance,type)",
     "legendFormat": "{{instance}}-{{type}}"
    }
   ]
  },
  {
   "title": "Schema Lease Error OPM",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(tidb_session_schema_lease_error_total[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}
{
 "title": "DDL",
 "panels": [
  {
   "title": "DDL Duration 95",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(tidb_ddl_handle_job_duration_seconds_bucket[1m])) by (le, type))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Batch Add Index Duration 100",
   "type": "graph",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(tidb_ddl_batch_add_idx_duration_seconds_bucket[1m])) by (le, type))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "DDL Waiting Jobs Count",
   "type": "graph",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "tidb_ddl_waiting_jobs", "legendFormat": "{{instance}}-{{type}}" }
   ]
  },
  {
   "title": "DDL META OPM",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(tidb_ddl_worker_operation_total[1m])",
     "legendFormat": "{{instance}}-{{type}}"
    }
   ]
  },
  {
   "title": "DDL Worker Duration 99",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(increase(tidb_ddl_worker_operation_duration_seconds_bucket[1m])) by (le, type, action, result))",
     "legendFormat": "{{type}}-{{action}}-{{result}}"
    }
   ]
  },
  {
   "title": "Deploy Syncer Duration",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(tidb_ddl_deploy_syncer_duration_seconds_bucket[2m])) by (le, type, result))",
     "legendFormat": "{{type}}-{{result}}"
    }
   ]
  },
  {
   "title": "Owner Handle Syncer Duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(tidb_ddl_owner_handle_syncer_duration_seconds_bucket[2m])) by (le, type, result))",
     "legendFormat": "{{type}}-{{result}}"
    }
   ]
  },
  {
   "title": "Update Self Version Duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(tidb_ddl_update_self_ver_duration_seconds_bucket[2m])) by (le, result))",
     "legendFormat": "{{result}}"
    }
   ]
  }
 ]
}
{
 "title": "Statistics",
 "panels": [
  {
   "title": "Auto Analyze Duration 95",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(tidb_statistics_auto_analyze_duration_bucket[1m])) by (le))",
     "legendFormat": "auto analyze duration"
    }
   ]
  },
  {
   "title": "Auto Analyze QPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tidb_statistics_auto_analyze_total[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Stats Inaccuracy Rate",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tidb_statistics_stats_inaccuracy_rate_bucket[1m])) by (le))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(tidb_statistics_stats_inaccuracy_rate_bucket[1m])) by (le))",
     "legendFormat": "90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(tidb_statistics_stats_inaccuracy_rate_bucket[1m])) by (le))",
     "legendFormat": "50"
    }
   ]
  },
  {
   "title": "Pseudo Estimation OPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tidb_statistics_pseudo_estimation_total[1m]))"
    }
   ]
  },
  {
   "title": "Dump Feedback OPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tidb_statistics_dump_feedback_total[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Update Stats OPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tidb_statistics_update_stats_total[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}
{
 "title": "Meta",
 "panels": [
  {
   "title": "AutoID QPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tidb_autoid_operation_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "AutoID Duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tidb_autoid_operation_duration_seconds_bucket[1m])) by (le, type))",
     "legendFormat": "99-{{type}}"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(tidb_autoid_operation_duration_seconds_bucket[1m])) by (le, type))",
     "legendFormat": "80-{{type}}"
    }
   ]
  },
  {
   "title": "Meta Operations Duration 99",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tidb_meta_operation_duration_seconds_bucket[1m])) by (le, type))",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}
{
 "title": "GC",
 "panels": [
  {
   "title": "Worker Action OPM",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(tidb_tikvclient_gc_worker_actions_total[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Duration 99",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tidb_tikvclient_gc_seconds_bucket[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Config",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(tidb_tikvclient_gc_config) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "GC Failure OPM",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(tidb_tikvclient_gc_failure[1m]))"
    }
   ]
  },
  {
   "title": "Action Result OPM",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(tidb_tikvclient_gc_action_result[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Too Many Locks Error OPM",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(tidb_tikvclient_gc_region_too_many_locks[1m]))"
    }
   ]
  }
 ]
}