{
 "title": "Test-Cluster-TiDB",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Query Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Duration",
     "type": "graph",
     "description": "TiDB query durations by histogram buckets with different percents",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "80"
      }
     ]
    },
    {
     "title": "QPS",
     "type": "graph",
     "description": "TiDB query processing numbers per second",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_server_query_total[1m])) by (result)",
       "legendFormat": "query {{result}}"
      }
     ]
    },
    {
     "title": "Statement OPS",
     "type": "graph",
     "description": "TiDB statement statistics by statement type",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_executor_statement_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "QPS By Instance",
     "type": "graph",
     "description": "TiDB query total statistics including both successful and failed ones",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(tidb_server_query_total[1m])",
       "legendFormat": "{{instance}} {{type}} {{result}}"
      }
     ]
    },
    {
     "title": "Failed Query OPM",
     "type": "graph",
     "description": "TiDB failed query statistics by query type",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(tidb_server_execute_error_total[1m])) by (type, instance)",
       "legendFormat": " {{type}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Slow query",
     "type": "graph",
     "description": "TiDB slow query statistics with slow query durations and coprocessor waiting/executing durations",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(tidb_server_slow_query_process_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "all_proc"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(tidb_server_slow_query_cop_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "all_cop_proc"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(tidb_server_slow_query_wait_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "all_cop_wait"
      }
     ]
    },
    {
     "title": "999 Duration",
     "type": "graph",
     "description": "TiDB durations for different query types with 99.9 percent buckets",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le,sql_type))",
       "legendFormat": "{{sql_type}}"
      }
     ]
    },
    {
     "title": "99 Duration",
     "type": "graph",
     "description": "TiDB durations for different query types with 99 percent buckets",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le,sql_type))",
       "legendFormat": "{{sql_type}}"
      }
     ]
    },
    {
     "title": "95 Duration",
     "type": "graph",
     "description": "TiDB durations for different query types with 95 percent buckets",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le,sql_type))",
       "legendFormat": "{{sql_type}}"
      }
     ]
    },
    {
     "title": "80 Duration",
     "type": "graph",
     "description": "TiDB durations for different query types with 80 percent buckets",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.80, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le,sql_type))",
       "legendFormat": "{{sql_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Duration 80 By Instance",
     "type": "graph",
     "description": "TiDB durations with 80 percent buckets by instance",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.80, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Duration 95 By Instance",
     "type": "graph",
     "description": "TiDB durations with 95 percent buckets by instance",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le, instance))",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Duration 99 By Instance",
     "type": "graph",
     "description": "TiDB durations with 99 percent buckets by instance",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Duration 999 By Instance",
     "type": "graph",
     "description": "TiDB durations with 99.9 percent buckets by instance",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Failed Query OPM Detail",
     "type": "graph",
     "description": "TiDB failed query statistics with failing infomation ",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(tidb_server_execute_error_total[1m])",
       "legendFormat": "{{type}} @ {{instance}}"
      }
     ]
    },
    {
     "title": "Internal SQL OPS",
     "type": "graph",
     "description": "The internal SQL is used by TiDB itself.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_session_restricted_sql_total[30s]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "graph",
     "description": "TiDB uptime since last restart",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "(time() - process_start_time_seconds{job=\"tidb\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "description": "TiDB process rss memory usage. TiDB heap memory size in use ",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"tidb\"}",
       "legendFormat": "process-{{instance}}"
      },
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"tidb\"}",
       "legendFormat": "heap-{{instance}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "TiDB cpu usage calculated with process cpu running seconds",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"tidb\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Connection Count",
     "type": "graph",
     "description": "TiDB current connection counts",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "tidb_server_connections", "legendFormat": "{{instance}}" },
      { "expr": "sum(tidb_server_connections)", "legendFormat": "total" }
     ]
    },
    {
     "title": "Open FD Count",
     "type": "graph",
     "description": "TiDB process opened file descriptors count",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{job=\"tidb\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Goroutine Count",
     "type": "graph",
     "description": "TiDB process current goroutines count",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " go_goroutines{job=~\"tidb.*\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Go GC Duration",
     "type": "graph",
     "description": "TiDB process Go garbage collection time cost",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "rate(go_gc_duration_seconds_sum{job=\"tidb\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Go Threads",
     "type": "graph",
     "description": "Total threads TiDB process created currently",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " go_threads{job=\"tidb\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Go GC Count",
     "type": "graph",
     "description": "The Go garbage collection counts per second",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " rate(go_gc_duration_seconds_count{job=\"tidb\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Go GC CPU Usage",
     "type": "graph",
     "description": "The fraction of this program's available CPU time used by the GC since the program started.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "go_memstats_gc_cpu_fraction{job=\"tidb\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Events OPM",
     "type": "graph",
     "description": "TiDB Server critical events total, including start/close/shutdown/hang etc",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(tidb_server_event_total[10m])",
       "legendFormat": "{{instance}}-server {{type}}"
      }
     ]
    },
    {
     "title": "Keep Alive OPM",
     "type": "graph",
     "description": "TiDB instance monitor average keep alive times",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(tidb_monitor_keep_alive_total[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Prepare Statement Count",
     "type": "graph",
     "description": "TiDB instance prepare statements count",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "tidb_server_prepared_stmts", "legendFormat": "{{instance}}" },
      {
       "expr": "sum(tidb_server_prepared_stmts)",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Time Jump Back OPS",
     "type": "graph",
     "description": "TiDB monitor time jump back count",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(tidb_monitor_time_jump_back_total[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Write Binlog Error",
     "type": "graph",
     "description": "TiDB instance critical errors count including panic etc",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(tidb_server_panic_total[1m])",
       "legendFormat": "panic-{{instance}}"
      },
      {
       "expr": "increase(tidb_server_critical_error_total[1m])",
       "legendFormat": "critical-{{instance}}"
      }
     ]
    },
    {
     "title": "Skip Binlog Count",
     "type": "graph",
     "description": "TiDB instance critical errors count including panic etc",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tidb_server_critical_error_total",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Get Token Duration",
     "type": "graph",
     "description": "Duration (us) for getting token, it should be small until concurrency limit is reached.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_server_get_token_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "99"
      }
     ]
    },
    {
     "title": "Handshake Error OPS",
     "type": "graph",
     "description": "TiDB processing handshake error count",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(tidb_server_handshake_error_total[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transaction OPS",
     "type": "graph",
     "description": "TiDB transaction processing counts by type and source. Internal means TiDB inner transcation calls",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_session_transaction_duration_seconds_count[1m])) by (type, sql_type)",
       "legendFormat": "{{type}}-{{sql_type}}"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "Bucketed histogram of transaction execution durations, including retry",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_session_transaction_duration_seconds_bucket[1m])) by (le, sql_type))",
       "legendFormat": "99-{{sql_type}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tidb_session_transaction_duration_seconds_bucket[1m])) by (le, sql_type))",
       "legendFormat": "95-{{sql_type}}"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(tidb_session_transaction_duration_seconds_bucket[1m])) by (le, sql_type))",
       "legendFormat": "80-{{sql_type}}"
      }
     ]
    },
    {
     "title": "Transaction Statement Num",
     "type": "graph",
     "description": "TiDB statements numbers within one transaction. Internal means TiDB inner transaction",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_session_transaction_statement_num_bucket[30s])) by (le, sql_type))",
       "legendFormat": "99-{{sql_type}}"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(tidb_session_transaction_statement_num_bucket[30s])) by (le, sql_type))",
       "legendFormat": "80-{{sql_type}}"
      }
     ]
    },
    {
     "title": "Transaction Retry Num",
     "type": "graph",
     "description": "TiDB transaction retry histogram bucket statistics",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1.0, sum(rate(tidb_session_retry_num_bucket[30s])) by (le))",
       "legendFormat": "100"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_session_retry_num_bucket[30s])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(tidb_session_retry_num_bucket[30s])) by (le))",
       "legendFormat": "90"
      }
     ]
    },
    {
     "title": "Session Retry Error OPS",
     "type": "graph",
     "description": "Error numbers of transaction retry",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_session_retry_error_total[30s])) by (type, sql_type)",
       "legendFormat": "{{type}}-{{sql_type}}"
      }
     ]
    },
    {
     "title": "Local Latch Wait Duration",
     "type": "graph",
     "description": "TiDB transaction latch wait time on key value storage",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_tikvclient_local_latch_wait_seconds_bucket[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tidb_tikvclient_local_latch_wait_seconds_bucket[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(tidb_tikvclient_local_latch_wait_seconds_bucket[1m])) by (le))",
       "legendFormat": "80"
      }
     ]
    },
    {
     "title": "KV Transaction OPS",
     "type": "graph",
     "description": "TiDB total kv transaction counts",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_tikvclient_txn_cmd_duration_seconds_count[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "KV Transaction Duration",
     "type": "graph",
     "description": "The duration of the transaction commit/rollback on TiKV.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_tikvclient_txn_cmd_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "99-{{type}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tidb_tikvclient_txn_cmd_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "95-{{type}}"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(tidb_tikvclient_txn_cmd_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "80-{{type}}"
      }
     ]
    },
    {
     "title": "Transaction Regions Num 90",
     "type": "graph",
     "description": "regions transaction operates on count",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(tidb_tikvclient_txn_regions_num_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Transaction Max Write KV Num",
     "type": "graph",
     "description": "kv write times per transaction execution",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(tidb_tikvclient_txn_write_kv_num_bucket[1m])) by (le, instance))",
       "legendFormat": "100 {{instance}}"
      }
     ]
    },
    {
     "title": "Transaction Max Write Size Bytes",
     "type": "graph",
     "description": "kv write size per transaction execution",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(tidb_tikvclient_txn_write_size_bytes_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Load Safepoint OPS",
     "type": "graph",
     "description": "safe point loading times",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_tikvclient_load_safepoint_total{type=\"ok\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Send HeartBeat Duration",
     "type": "graph",
     "description": "When the pessimistic transaction begins to work, it will send heartbeat requests to update its TTL. \nThis metric is the latency of the send heartbeat operation.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.80, sum(rate(tidb_tikvclient_txn_heart_beat_bucket[1m])) by (le, type))",
       "legendFormat": "80-{{type}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tidb_tikvclient_txn_heart_beat_bucket[1m])) by (le, type))",
       "legendFormat": "95-{{type}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_tikvclient_txn_heart_beat_bucket[1m])) by (le, type))",
       "legendFormat": "99-{{type}}"
      }
     ]
    },
    {
     "title": "TTL Lifetime Reach Counter",
     "type": "graph",
     "description": "This metric means the pessimistic lives too long which is abnormal.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {}
     ]
    }
   ]
  },
  {
   "title": "Executor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Parse Duration",
     "type": "graph",
     "description": "The time cost of parsing SQL to AST",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(tidb_session_parse_duration_seconds_bucket[1m])) by (le, sql_type))",
       "legendFormat": "{{sql_type}}"
      }
     ]
    },
    {
     "title": "Compile Duration",
     "type": "graph",
     "description": "The time cost of building the query plan",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(tidb_session_compile_duration_seconds_bucket[1m])) by (le, sql_type))",
       "legendFormat": "{{sql_type}}"
      }
     ]
    },
    {
     "title": "Execution Duration",
     "type": "graph",
     "description": "The time cost of executing the SQL which does not include the time to get the results of the query .",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(tidb_session_execute_duration_seconds_bucket[1m])) by (le, sql_type))",
       "legendFormat": "{{sql_type}}"
      }
     ]
    },
    {
     "title": "Expensive Executors OPS",
     "type": "graph",
     "description": "TiDB executors using more cpu and memory resources",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_executor_expensive_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Queries Using Plan Cache OPS",
     "type": "graph",
     "description": "TiDB plan cache hit total",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_server_plan_cache_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Distsql",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distsql Duration",
     "type": "graph",
     "description": "durations of distsql execution by type",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 122 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(tidb_distsql_handle_query_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "999-{{type}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_distsql_handle_query_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "99-{{type}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(tidb_distsql_handle_query_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "90-{{type}}"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(tidb_distsql_handle_query_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "50-{{type}}"
      }
     ]
    },
    {
     "title": "Distsql QPS",
     "type": "graph",
     "description": "distsql query handling durations per second",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 122 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_distsql_handle_query_duration_seconds_count[1m]))"
      }
     ]
    },
    {
     "title": "Distsql Partial QPS",
     "type": "graph",
     "description": "the numebr of distsql partial scan numbers",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 129 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_distsql_scan_keys_partial_num_count[1m]))"
      }
     ]
    },
    {
     "title": "Scan Keys Num",
     "type": "graph",
     "description": "the numebr of distsql scan numbers",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 129 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(tidb_distsql_scan_keys_num_bucket[1m])) by (le))",
       "legendFormat": "100"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(tidb_distsql_scan_keys_num_bucket[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(tidb_distsql_scan_keys_num_bucket[1m])) by (le))",
       "legendFormat": "50"
      }
     ]
    },
    {
     "title": "Scan Keys Partial Num",
     "type": "graph",
     "description": "the numebr of distsql partial scan key numbers",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 129 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(tidb_distsql_scan_keys_partial_num_bucket[1m])) by (le))",
       "legendFormat": "100"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(tidb_distsql_scan_keys_partial_num_bucket[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(tidb_distsql_scan_keys_partial_num_bucket[1m])) by (le))",
       "legendFormat": "50"
      }
     ]
    },
    {
     "title": "Partial Num",
     "type": "graph",
     "description": "distsql partial numbers per query",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 136 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(tidb_distsql_partial_num_bucket[1m])) by (le))",
       "legendFormat": "100"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(tidb_distsql_partial_num_bucket[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(tidb_distsql_partial_num_bucket[1m])) by (le))",
       "legendFormat": "50"
      }
     ]
    },
    {
     "title": "Coprocessor Seconds 999",
     "type": "graph",
     "description": "kv storage coprocessor processing durations",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 136 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(tidb_tikvclient_cop_duration_seconds_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "KV Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "KV Backoff Duration",
     "type": "graph",
     "description": "kv backoff time durations by type",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(tidb_tikvclient_backoff_seconds_bucket[1m])) by (le))",
       "legendFormat": "999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_tikvclient_backoff_seconds_bucket[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(tidb_tikvclient_backoff_seconds_bucket[1m])) by (le))",
       "legendFormat": "80"
      }
     ]
    },
    {
     "title": "TiClient Region Error OPS",
     "type": "graph",
     "description": "kv region error times",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_tikvclient_region_err_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "KV Backoff OPS",
     "type": "graph",
     "description": "kv storage backoff times",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_tikvclient_backoff_seconds_count[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Lock Resolve OPS",
     "type": "graph",
     "description": "lock resolve times",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_tikvclient_lock_resolver_actions_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Other Errors OPS",
     "type": "graph",
     "description": "lock cleanup failed times and safe point update times",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_tikvclient_lock_cleanup_task_total[1m])) by (type)",
       "legendFormat": "cleanup_secondary_failure_{{type}}"
      },
      {
       "expr": "sum(rate(tidb_tikvclient_load_safepoint_total{type=\"fail\"}[1m]))",
       "legendFormat": "load_safepoint_failure"
      }
     ]
    }
   ]
  },
  {
   "title": "KV Request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "KV Request OPS",
     "type": "graph",
     "description": "kv request total by instance and command type",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_tikvclient_request_seconds_count[1m])) by (instance, type)",
       "legendFormat": "{{instance}}-{{type}}"
      }
     ]
    },
    {
     "title": "KV Request Duration 99 by store",
     "type": "graph",
     "description": "kv requests durations by store",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_tikvclient_request_seconds_bucket{type!=\"GC\"}[1m])) by (le, store))",
       "legendFormat": "store-{{store}}"
      }
     ]
    },
    {
     "title": "KV Request Duration 99 by type",
     "type": "graph",
     "description": "kv request durations by request type",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_tikvclient_request_seconds_bucket{type!=\"GC\"}[1m])) by (le,type))",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PD Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "PD Client CMD OPS",
     "type": "graph",
     "description": "pd command count by type",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_client_cmd_handle_cmds_duration_seconds_count{type!=\"tso\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "PD Client CMD Duration",
     "type": "graph",
     "description": "pd client command durations by type within 99.9 percent buckets",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(pd_client_cmd_handle_cmds_duration_seconds_bucket{type!~\"tso|tso_async_wait\"}[1m])) by (le, type))",
       "legendFormat": "999-{{type}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_client_cmd_handle_cmds_duration_seconds_bucket{type!~\"tso|tso_async_wait\"}[1m])) by (le, type))",
       "legendFormat": "99-{{type}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(pd_client_cmd_handle_cmds_duration_seconds_bucket{type!~\"tso|tso_async_wait\"}[1m])) by (le, type))",
       "legendFormat": "90-{{type}}"
      }
     ]
    },
    {
     "title": "PD Client CMD Fail OPS",
     "type": "graph",
     "description": "pd client command fail count by type",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_client_cmd_handle_failed_cmds_duration_seconds_count[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "PD TSO OPS",
     "type": "graph",
     "description": "The duration of a client calling GetTSAsync until received the TS result.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_client_cmd_handle_cmds_duration_seconds_count{type=\"tso\"}[1m]))",
       "legendFormat": "cmd"
      },
      {
       "expr": "sum(rate(pd_client_request_handle_requests_duration_seconds_count{type=\"tso\"}[1m]))",
       "legendFormat": "request"
      }
     ]
    },
    {
     "title": "PD TSO Wait Duration",
     "type": "graph",
     "description": "The duration of a client starting to wait for the TS until received the TS result.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(pd_client_cmd_handle_cmds_duration_seconds_bucket{type=\"wait\"}[1m])) by (le))",
       "legendFormat": "999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_client_cmd_handle_cmds_duration_seconds_bucket{type=\"wait\"}[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(pd_client_cmd_handle_cmds_duration_seconds_bucket{type=\"wait\"}[1m])) by (le))",
       "legendFormat": "90"
      }
     ]
    },
    {
     "title": "PD TSO RPC Duration",
     "type": "graph",
     "description": "The duration of a client sending TSO request until received the response.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(pd_client_request_handle_requests_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "legendFormat": "999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_client_request_handle_requests_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(pd_client_request_handle_requests_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "legendFormat": "90"
      }
     ]
    },
    {
     "title": "Start TSO Wait Duration",
     "type": "graph",
     "description": "The duration of the waiting time for getting the start timestamp oracle",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(tidb_pdclient_ts_future_wait_seconds_bucket[1m])) by (le))",
       "legendFormat": "999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_pdclient_ts_future_wait_seconds_bucket[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(tidb_pdclient_ts_future_wait_seconds_bucket[1m])) by (le))",
       "legendFormat": "90"
      }
     ]
    }
   ]
  },
  {
   "title": "Schema Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load Schema Duration",
     "type": "graph",
     "description": "TiDB loading schema time durations by instance",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_domain_load_schema_duration_seconds_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Load Schema OPS",
     "type": "graph",
     "description": "TiDB loading schema times including both failed and successful ones",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_domain_load_schema_total[1m])) by (instance,type)",
       "legendFormat": "{{instance}}-{{type}}"
      }
     ]
    },
    {
     "title": "Schema Lease Error OPM",
     "type": "graph",
     "description": "TiDB schema lease error counts",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(tidb_session_schema_lease_error_total[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Load Privilege OPS",
     "type": "graph",
     "description": "TiDB load privilege counts",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_domain_load_privilege_total[1m])) by (instance,type)",
       "legendFormat": "{{instance}}-{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DDL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "DDL Duration 95",
     "type": "graph",
     "description": "TiDB DDL duration statistics",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(tidb_ddl_handle_job_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Batch Add Index Duration 100",
     "type": "graph",
     "description": "TiDB batch add index durations by histogram buckets",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(tidb_ddl_batch_add_idx_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(rate(tidb_ddl_add_index_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "DDL Waiting Jobs Count",
     "type": "graph",
     "description": "TiDB ddl request in queue",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      { "expr": "tidb_ddl_waiting_jobs", "legendFormat": "{{instance}}-{{type}}" }
     ]
    },
    {
     "title": "DDL META OPM",
     "type": "graph",
     "description": "TiDB different ddl worker numbers",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(tidb_ddl_worker_operation_total[1m])",
       "legendFormat": "{{instance}}-{{type}}"
      }
     ]
    },
    {
     "title": "DDL Worker Duration 99",
     "type": "graph",
     "description": "TiDB worker duration by type, action, results",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(increase(tidb_ddl_worker_operation_duration_seconds_bucket[1m])) by (le, type, action, result))",
       "legendFormat": "{{type}}-{{action}}-{{result}}"
      }
     ]
    },
    {
     "title": "Deploy Syncer Duration",
     "type": "graph",
     "description": "TiDB ddl schema syncer statistics, including init, start, watch, clear function call time cost",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(tidb_ddl_deploy_syncer_duration_seconds_bucket[2m])) by (le, type, result))",
       "legendFormat": "{{type}}-{{result}}"
      }
     ]
    },
    {
     "title": "Owner Handle Syncer Duration",
     "type": "graph",
     "description": "TiDB ddl owner time operations on etcd duration statistics ",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(tidb_ddl_owner_handle_syncer_duration_seconds_bucket[2m])) by (le, type, result))",
       "legendFormat": "{{type}}-{{result}}"
      }
     ]
    },
    {
     "title": "Update Self Version Duration",
     "type": "graph",
     "description": "TiDB schema syncer version update time duration",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(tidb_ddl_update_self_ver_duration_seconds_bucket[2m])) by (le, result))",
       "legendFormat": "{{result}}"
      }
     ]
    },
    {
     "title": "DDL OPM",
     "type": "graph",
     "description": "executed DDL jobs per minute",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_ddl_handle_job_duration_seconds_count[1m])) by (type)",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "sum(rate(tidb_ddl_handle_job_duration_seconds_count[1m]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "DDL add index progress in percentage",
     "type": "graph",
     "description": "TiDB DDL add index progress in percentage. The value is [0,100]",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tidb_ddl_add_index_percentage_progress",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Auto Analyze Duration 95",
     "type": "graph",
     "description": "TiDB auto analyze time durations within 95 percent histogram buckets",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 149 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(tidb_statistics_auto_analyze_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "auto analyze duration"
      }
     ]
    },
    {
     "title": "Auto Analyze QPS",
     "type": "graph",
     "description": "TiDB auto analyze query per second",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 149 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_statistics_auto_analyze_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Stats Inaccuracy Rate",
     "type": "graph",
     "description": "TiDB statistics inaccurate rate",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 149 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_statistics_stats_inaccuracy_rate_bucket[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(tidb_statistics_stats_inaccuracy_rate_bucket[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(tidb_statistics_stats_inaccuracy_rate_bucket[1m])) by (le))",
       "legendFormat": "50"
      }
     ]
    },
    {
     "title": "Pseudo Estimation OPS",
     "type": "graph",
     "description": "TiDB optimizer using pseudo estimation counts",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 156 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_statistics_pseudo_estimation_total[1m]))",
       "legendFormat": "Pseudo OPS"
      }
     ]
    },
    {
     "title": "Dump Feedback OPS",
     "type": "graph",
     "description": "TiDB dumping statistics back to kv storage times",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 156 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_statistics_dump_feedback_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Store Query Feedback QPS",
     "type": "graph",
     "description": "TiDB store quering feedback counts",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 156 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_statistics_store_query_feedback_total[1m])) by (type) ",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Significant Feedback",
     "type": "graph",
     "description": "Counter of query feedback whose actual count is much different than calculated by current statistics",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 163 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_statistics_high_error_rate_feedback_total[1m]))",
       "legendFormat": "Significant Feedback"
      }
     ]
    },
    {
     "title": "Update Stats OPS",
     "type": "graph",
     "description": "TiDB updating statistics using feed back counts",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 163 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_statistics_update_stats_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Fast Analyze Status 100",
     "type": "graph",
     "description": "TiDB fast analyze statistics ",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 163 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(tidb_statistics_fast_analyze_status_bucket[1m])) by (le, type))",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Owner",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "New ETCD Session Duration 95",
     "type": "graph",
     "description": "TiDB new session durations for new etcd sessions",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 150 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(tidb_owner_new_session_duration_seconds_bucket[1m])) by (le, instance, result))",
       "legendFormat": "{{instance}}-{{result}}"
      }
     ]
    },
    {
     "title": "Owner Watcher OPS",
     "type": "graph",
     "description": "TiDB owner  watcher counts",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 150 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_owner_watch_owner_total[1m])) by (type, result, instance)",
       "legendFormat": "{{type}}-{{result}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Owner Watcher OPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 150 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_owner_watch_owner_total[1m])) by (type, result, instance)",
       "legendFormat": "{{type}}-{{result}}-{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Meta",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "AutoID QPS",
     "type": "graph",
     "description": "TiDB auto id requests per second including  single table/global auto id processing and single table auto id rebase processing",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 151 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_autoid_operation_duration_seconds_count[1m]))",
       "legendFormat": "AutoID QPS"
      }
     ]
    },
    {
     "title": "AutoID Duration",
     "type": "graph",
     "description": "TiDB auto id requests durations",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 151 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_autoid_operation_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "99-{{type}}"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(tidb_autoid_operation_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "80-{{type}}"
      }
     ]
    },
    {
     "title": "Region Cache Error OPS",
     "type": "graph",
     "description": "TiDB region cache operations count",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 158 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_tikvclient_region_cache_operations_total{result=\"err\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Meta Operations Duration 99",
     "type": "graph",
     "description": "TiDB meta operation durations including get/set schema and ddl jobs",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 158 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_meta_operation_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Worker Action OPM",
     "type": "graph",
     "description": "kv storage garbage collection counts by type",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 152 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(tidb_tikvclient_gc_worker_actions_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Duration 99",
     "type": "graph",
     "description": "kv storage garbage collection time durations",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 152 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_tikvclient_gc_seconds_bucket[1m])) by (le))",
       "legendFormat": "99"
      }
     ]
    },
    {
     "title": "Config",
     "type": "graph",
     "description": "kv storage garbage collection config including gc_life_time and gc_run_interval",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 152 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(tidb_tikvclient_gc_config) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "GC Failure OPM",
     "type": "graph",
     "description": "kv storage garbage collection failing counts",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 159 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(tidb_tikvclient_gc_failure[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Delete Range Failure OPM",
     "type": "graph",
     "description": "kv storage unsafe destroy range failed counts",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 159 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(tidb_tikvclient_gc_unsafe_destroy_range_failures[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Too Many Locks Error OPM",
     "type": "graph",
     "description": "kv storage region garbage collection clean too many locks count",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 159 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(tidb_tikvclient_gc_region_too_many_locks[1m]))",
       "legendFormat": "Locks Error OPM"
      }
     ]
    },
    {
     "title": "Action Result OPM",
     "type": "graph",
     "description": "kv storage garbage collection results including failed and successful ones",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 166 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(tidb_tikvclient_gc_action_result[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Delete Range Task Status",
     "type": "graph",
     "description": "kv storage delete range task execution status by type",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 166 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(tidb_tikvclient_range_task_stats) by (type, result)",
       "legendFormat": "{{type}}-{{result}}"
      }
     ]
    },
    {
     "title": "Push Task Duration 95",
     "type": "graph",
     "description": "kv storage range worker processing one task duration",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 166 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(tidb_tikvclient_range_task_push_duration_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Batch Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pending Request Count by TiKV",
     "type": "graph",
     "description": "kv storage batch requests in queue",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 153 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(tidb_tikvclient_pending_batch_requests) by (store)",
       "legendFormat": "{{store}}"
      }
     ]
    },
    {
     "title": "Wait Duration 95",
     "type": "graph",
     "description": "kv storage batch processing durations",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 153 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(tidb_tikvclient_batch_wait_duration_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Batch Client Unavailable Duration 95",
     "type": "graph",
     "description": "kv storage batch processing unvailable durations",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 153 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(tidb_tikvclient_batch_client_unavailable_seconds_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}