{
 "title": "Test-Cluster-Pods",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=~\"TIDB_NAMESPACE\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{cluster=\"$cluster\", namespace=\"TIDB_NAMESPACE\", pod=\"$pod\"}, container)"
   },
   {
    "name": "pvc",
    "query": "label_values(kubelet_volume_stats_capacity_bytes{namespace=~\"TIDB_NAMESPACE\"},persistentvolumeclaim)"
   }
  ]
 },
 "panels": [
  { "title": "PV Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PVC Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=\"TIDB_NAMESPACE\"}) by (persistentvolumeclaim) * on (persistentvolumeclaim) group_left\n(storageclass) kube_persistentvolumeclaim_info{namespace=\"TIDB_NAMESPACE\"})"
    },
    {
     "expr": "kube_persistentvolumeclaim_status_phase{namespace=\"TIDB_NAMESPACE\"} == 1"
    }
   ]
  },
  {
   "title": "Volume Space Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_capacity_bytes{job=\"kubelet\", persistentvolumeclaim=\"$pvc\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "kubelet_volume_stats_used_bytes{job=\"kubelet\", persistentvolumeclaim=\"$pvc\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "kubelet_volume_stats_available_bytes{job=\"kubelet\", persistentvolumeclaim=\"$pvc\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Service Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service Info",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "(kube_service_spec_type{namespace=\"TIDB_NAMESPACE\"} * on (service, namespace) group_left(cluster_ip ) kube_service_info{namespace=\"TIDB_NAMESPACE\"}) * on (namespace, service) group_left(Value)\n sum(label_replace(kube_endpoint_address_available{namespace=\"TIDB_NAMESPACE\"}, \"service\", \"$0\", \"endpoint\", \".*\")) by (namespace, service)",
       "legendFormat": "Avaliable Endpoint Number"
      }
     ]
    }
   ]
  },
  { "title": "Pod Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Pod Image Version",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{pod=\"$pod\",namespace=\"TIDB_NAMESPACE\"}) by (pod, container, image)"
    }
   ]
  },
  {
   "title": "Pod Mapping",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"TIDB_NAMESPACE\", pod=\"$pod\"} * on(namespace, pod) group_left(phase) (kube_pod_status_phase{namespace=\"TIDB_NAMESPACE\", pod=\"$pod\"} == 1)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{ namespace=\"TIDB_NAMESPACE\", pod_name=\"$pod\", container_name!=\"POD\", container_name!=\"\"}) by (container_name)",
     "legendFormat": "{{container_name}} (RSS)"
    },
    {
     "expr": "sum(container_memory_cache{namespace=\"TIDB_NAMESPACE\", pod_name=\"$pod\", container_name!=\"POD\", container_name!=\"\"}) by (container_name)",
     "legendFormat": "{{container_name}} (Cache)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{ namespace=\"TIDB_NAMESPACE\", pod_name=\"$pod\", container_name!=\"POD\", container_name!=\"\"}) by (container_name)",
     "legendFormat": "{{container_name}} (WorkingSet)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{ namespace=\"TIDB_NAMESPACE\", pod=\"$pod\"}) by (namespace, pod, container)",
     "legendFormat": "{{container}} (Limit)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{ namespace=\"TIDB_NAMESPACE\", pod=\"$pod\"}) by (namespace, pod, container)",
     "legendFormat": "{{container}} (Request)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name) (rate(container_cpu_usage_seconds_total{job=\"kubelet\", cluster=\"$cluster\", namespace=\"TIDB_NAMESPACE\", image!=\"\", pod_name=\"$pod\", container_name=~\"$container\", container_name!=\"POD\"}[1m]))",
     "legendFormat": "Current: {{ container_name }}"
    },
    {
     "expr": "sum by(container) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"TIDB_NAMESPACE\", resource=\"cpu\", pod=\"$pod\", container=~\"$container\"})",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "sum by(container) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"TIDB_NAMESPACE\", resource=\"cpu\", pod=\"$pod\", container=~\"$container\"})",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod_name) (rate(container_network_receive_bytes_total{job=\"kubelet\", cluster=\"$cluster\", namespace=\"TIDB_NAMESPACE\", pod_name=\"$pod\"}[1m])))",
     "legendFormat": "RX"
    },
    {
     "expr": "sort_desc(sum by (pod_name) (rate(container_network_transmit_bytes_total{job=\"kubelet\", cluster=\"$cluster\", namespace=\"TIDB_NAMESPACE\", pod_name=\"$pod\"}[1m])))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Pod Disk IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod_name=\"$pod\",container_name=\"$container\"}[1m])) by (container_name,device)",
     "legendFormat": "Write: {{container_name}}-{{device}}"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{pod_name=\"$pod\",container_name=\"$container\"}[1m])) by (container_name,device)",
     "legendFormat": "Read: {{container_name}}-{{device}}"
    }
   ]
  }
 ]
}